name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (for React)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build and Test React App
        working-directory: ./client
        run: |
          npm install
          npm run build

      - name: Set up Node.js (for Node.js server)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build and Test Node.js Server
        working-directory: ./server
        run: |
          npm install
          npm start
